spring:
  application:
    name: ecomm-service
  config:
    import:  "optional:configserver:http://localhost:8088"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ecommdb
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
#
#ecomm_service:
#  jwtSecret: BLUEYONDERBELLANDURBENGALURUBLUEYONDERBELLANDURBENGALURUBLUEYONDERBELLANDURBENGALURUBENGALURUBLUEYONDERBELLANDURBENGALURUBENGALURUBLUEYONDERBELLANDURBENGALURU
#  jwtExpirationMs: 86400000

springdoc:
  swagger-ui:
    enabled: true
    layout: BaseLayout
    path: /swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /api-docs
